name: Focal Builder

on:
  push:
    paths:
    - 'Focal'
    - '.github/workflows/focal.yml'
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
          username: rzlamrr
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & Push Focal
      run: bash build.sh focal

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: bash build.sh test focal
