name: Lite Builder

on:
  push:
    paths:
    - 'Lite'
    - '.github/workflows/lite.yml'
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
          username: rzlamrr
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & Push Lite
      run: bash build.sh lite

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: bash build.sh test lite
